### ISSUE TITLE
After booting there is no everest folder inside /etc folder

### ISSUE THREAD

**Issue by VishuAVL** [chargebyte/chargebyte-docs#12]
After booting up charge control c board and doing ssh to it. There is no everest folder inside /etc and no configuration of the CbTarragonDriver module can be found in “/usr/libexec/everest/modules/CbTarragonDriver” directory.

**Comment by FaHaGit** [comment]
Hello VishuAVL,

Thank you for the feedback! Do you have already installed a chargebyte EVerest image (e.g. v.0.10.0)?

Unfortunately, there is currently no note in the documentation that EVerest must first be installed on existing boards with old chargebyte firmware.

Please contact our support desk (a link to the support desk can be also found in the "Toubleshooting" section), if you have already installed EVerest or if you have issues with installing it.

Best regards

**Comment by VishuAVL** [comment]
Hello FaHaGit,

Thank You for the response. I haven't installed any new firmware image on the board. It is preinstalled image only.
So, now I have to install EVerest on the board manually?
https://github.com/EVerest/everest-core
By following this link??

Thank You and Regards

**Comment by FaHaGit** [comment]
Hello VishuAVL,

Please contact [our support desk](https://chargebyte.com/support) regarding the chargebyte EVerest 0.10.0 image and a short introduction on how to install the image.

We will expand the user guide in the next few days and add a section on how to update boards with old chargebyte images to the current EVerest image.

Best regards

**Comment by VishuAVL** [comment]
Hello FaHaGit,

Thank you for the help. I will contact the support desk.

Warm regards

**Comment by VishuAVL** [comment]
Hello FahaGit,

I am not getting access for the support desk. They are not allowing it.

Thank you

**Comment by lategoodbye** [comment]
Hi @VishuAVL,
can you please post the following information:
- the URL you are trying to access
- the exact error message

**Comment by VishuAVL** [comment]
Hi @lategoodbye,

1. I am trying to access this link attached here.

https://chargebyte.atlassian.net/servicedesk/customer/portal/3/user/login?destination=portal%2F3

2. The error message it is showing is as follows:

"We couldn't give you access. Use another email and try again."

Thank You

**Comment by lategoodbye** [comment]
Hi @VishuAVL,
did you already send an email to info@chargebyte.com ?

**Comment by VishuAVL** [comment]
Hi @lategoodbye,
No, I haven't send any mail.

**Comment by VishuAVL** [comment]
Then, what should I do. I have tried with other email iDs also but its showing same thing. Should I try with sending male to info@chargebyte.com.

**Comment by lategoodbye** [comment]
Yes, please

**Comment by FaHaGit** [comment]
Hi @VishuAVL,

In the meantime, we have also updated the User Guide regarding the software update process. Please follow the "Firmware Update" section of the "Getting Started" chapter of the User Guide.

If you were able to successfully install the image and see the EVerest directory structures it would be nice to get feedback so that we can close the issue.

Tank you and best regards

**Comment by VishuAVL** [comment]
Hi @FaHaGit,
Yes, I was able to successfully install the image and see the directory.

Thank You and Warm Regards

**Comment by FaHaGit** [comment]
Thank you for the feedback!
